name: PR pipeline

on:
  pull_request: 
    types: 
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Build project
        run: dotnet build ./src/lib/*.csproj -c Release

  test:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Run tests
        run: dotnet test ./*.slnx

  pre-release:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/dotnet/sdk:9.0
      env: 
        Nuget_Test_Pat: ${{ secrets.GITHUB_TOKEN }}
        
    permissions: 
      packages: write
    needs:
      - build
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Nerdbank.GitVersioning
        uses: dotnet/nbgv@v0.4.2
        id: version
      - name: Test output for secret
        run: echo $Nuget_Test_Pat
      - name: Calculate Pre-release Suffix
        id: suffix
        run: |
          PR_NUMBER=$(echo $GITHUB_REF_NAME | cut -d'/' -f1)
          echo "PR-Number: $PR_NUMBER"
          echo "PR Run-Number: $GITHUB_RUN_NUMBER"
          echo "suffix=rc-pr-${PR_NUMBER}-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
      - name: Output Pre-release Suffix
        run: echo "Suffix=${{ steps.suffix.outputs.suffix }}"
      # - name: Pack and Bundle package
      #   run: |
      #     dotnet pack ./src/lib/*.csproj -c Release /p:NBGV_Prerelease=${{ steps.suffix.outputs.suffix }} --version-suffix ${{ steps.suffix.outputs.suffix }}
      # - name: Add nuget package source
      #   run: |
      #     dotnet nuget add source --username $GITHUB_REPOSITORY_OWNER --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/jk-atbas/index.json"
      # - name: Push to nuget registry
      #   run: dotnet nuget push ./src/lib/bin/Release/*.nupkg --api-key "${{ secrets.GITHUB_TOKEN }}" --source github --skip-duplicate
